### PR TITLE
Add Hugging Face public dataset footers

### PR DESCRIPTION
**Pull request by alkis**
These are footers from some public datasets from [Hugging Face](http://huggingface.co/).

* https://huggingface.co/datasets/fancyzhx/amazon_polarity
* https://huggingface.co/datasets/cogsci13/Amazon-Reviews-2023-Books-Review
* https://huggingface.co/datasets/hfl/cmrc2018
* https://huggingface.co/datasets/HuggingFaceTB/everyday-conversations-llama3.1-2k

### CODE REVIEW

**Comment by emkornfield** [comment]
@alkis I don't think can include parquet data from the first two links, as I can't find a license for the data.  The second two links seem to be explicitly licensed under Apache 2.0 and MIT so can be included.

**Comment by emkornfield** [comment]
Can we add a LICENSE file with attribute the files we end up including along with there license?

**Comment by Fokko** [comment]
I don't think we're going to make releases of these files, but I agree with @emkornfield that is important to only use [compatible licenses](https://www.apache.org/legal/resolved.html#category-a).

@alkis You can find an example of a LICENSE file here: https://github.com/apache/iceberg/blob/cd32ec76ecd2866c05185065e4ed7196121de49a/LICENSE#L206

**Comment by alkis** [comment]
Removed ones without licenses and added those with an explicit open source one. Added a README in the subdirectory with a table of licenses.

**Review by Fokko — APPROVED** [review]

**Comment by nongli-db** [comment]
@Fokko hey Fokko, how is this repo set up? Who/how can we merge into it?

**Comment by alkis** [comment]
@emkornfield could you merge this please?

**Comment by wgtmac** [comment]
I just merged this. Thanks @alkis!

**Pull request merged**
